name: ci-cd-environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.1.2
  - black=23.3.0
  - flake8=6.1.0
  - autopep8=2.0.2
  - isort=5.12.0
  - clang-format=16.0.6
  - make
  - setuptools=68.0.0
  - nbstripout
