name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

# Default shell for all run steps
defaults:
  run:
    shell: bash -l {0}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Online Document
      run: |
        git config --local --get remote.origin.url
        cd docs/build_docs
        bash build.sh latest

    - name: Push to github
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build_tmp/gh-pages
        publish_branch: gh-pages